FROM nginx:1.29.1-alpine-slim

RUN rm -r /usr/share/nginx/html \
    && mkdir -p /usr/share/nginx/html \
    && mkdir -p /etc/nginx/conf.d

WORKDIR /usr/share/nginx/html

ADD ./apps/web/dist .

COPY ./apps/web/infra/default.conf /etc/nginx/conf.d/default.conf

EXPOSE 8080

CMD ["nginx", "-g", "daemon off;"]
