version: 2

registries:
  # Workaround https://github.com/dependabot/dependabot-core/issues/15415
  public:
    type: npm-registry
    url: https://registry.npmjs.org/
    token: ${{ secrets.DEPENDABOT_NULL_TOKEN }}
    replaces-base: true

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 3 # 1 day after pnpm's cutoff, prevent a race
    groups:
      tanstack:
        patterns:
          - "@tanstack/*"
      react-ecosystem:
        patterns:
          - react
          - react-dom
          - "@types/react*"
