version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 3 # 1 day after pnpm's cutoff, prevent a race
    open-pull-requests-limit: 10 # Increase PR limit
    groups:
      tanstack:
        patterns:
          - "@tanstack/*"
      radix-ui:
        patterns:
          - "@radix-ui/*"
      react-ecosystem:
        patterns:
          - react
          - react-dom
          - "@types/react*"
