project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
base_path: "."
base_url: "https://meshtastic.crowdin.com/api/v2"

preserve_hierarchy: true

files:
  - source: "/public/i18n/locales/en/*.json"
    translation: "/public/i18n/locales/%locale%/%original_file_name%"
