name: Feature Request
description: Request a new feature
title: "[Feature Request]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your request. While we can't guarantee implementation, all requests will be carefully reviewed.
  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm the following before submitting your feature request
      options:
        - label: I have searched existing issues to ensure this feature hasn't already been requested
          required: true
        - label: I have checked the documentation to verify this feature doesn't already exist
          required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem are you trying to solve? Describe the challenge or limitation you're facing.
      placeholder: I'm frustrated when...
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your idea for solving the problem. What would you like to see implemented?
      placeholder: It would be great if...
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Current Alternatives
      description: Are there any workarounds or alternative solutions you're currently using?
      placeholder: Currently, I'm working around this by...
    validations:
      required: false
  - type: dropdown
    id: importance
    attributes:
      label: Importance
      description: How important is this feature to you?
      options:
        - Nice to have
        - Important
        - Critical
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, mockups, or examples that might help us understand your request better.
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this feature request!
