import type { FieldRegistryEntry } from "../types.ts";

export const moduleFieldRegistry: FieldRegistryEntry[] = [
  {
    section: "module",
    tab: "mqtt",
    groupLabelKey: "mqtt.title",
    groupNamespace: "moduleConfig",
    fields: [
      {
        name: "enabled",
        labelKey: "mqtt.enabled.label",
        descriptionKey: "mqtt.enabled.description",
        namespace: "moduleConfig",
      },
      {
        name: "address",
        labelKey: "mqtt.address.label",
        descriptionKey: "mqtt.address.description",
        namespace: "moduleConfig",
      },
      {
        name: "username",
        labelKey: "mqtt.username.label",
        descriptionKey: "mqtt.username.description",
        namespace: "moduleConfig",
      },
      {
        name: "password",
        labelKey: "mqtt.password.label",
        descriptionKey: "mqtt.password.description",
        namespace: "moduleConfig",
      },
      {
        name: "encryptionEnabled",
        labelKey: "mqtt.encryptionEnabled.label",
        descriptionKey: "mqtt.encryptionEnabled.description",
        namespace: "moduleConfig",
      },
      {
        name: "jsonEnabled",
        labelKey: "mqtt.jsonEnabled.label",
        descriptionKey: "mqtt.jsonEnabled.description",
        namespace: "moduleConfig",
      },
      {
        name: "tlsEnabled",
        labelKey: "mqtt.tlsEnabled.label",
        descriptionKey: "mqtt.tlsEnabled.description",
        namespace: "moduleConfig",
      },
      {
        name: "root",
        labelKey: "mqtt.root.label",
        descriptionKey: "mqtt.root.description",
        namespace: "moduleConfig",
      },
      {
        name: "proxyToClientEnabled",
        labelKey: "mqtt.proxyToClientEnabled.label",
        descriptionKey: "mqtt.proxyToClientEnabled.description",
        namespace: "moduleConfig",
      },
      {
        name: "mapReportingEnabled",
        labelKey: "mqtt.mapReportingEnabled.label",
        descriptionKey: "mqtt.mapReportingEnabled.description",
        namespace: "moduleConfig",
      },
      {
        name: "mapReportSettings.publishIntervalSecs",
        labelKey: "mqtt.mapReportSettings.publishIntervalSecs.label",
        descriptionKey:
          "mqtt.mapReportSettings.publishIntervalSecs.description",
        namespace: "moduleConfig",
      },
      {
        name: "mapReportSettings.positionPrecision",
        labelKey: "mqtt.mapReportSettings.positionPrecision.label",
        descriptionKey: "mqtt.mapReportSettings.positionPrecision.description",
        namespace: "moduleConfig",
      },
    ],
  },
  {
    section: "module",
    tab: "serial",
    groupLabelKey: "serial.title",
    groupNamespace: "moduleConfig",
    fields: [
      {
        name: "enabled",
        labelKey: "serial.enabled.label",
        descriptionKey: "serial.enabled.description",
        namespace: "moduleConfig",
      },
      {
        name: "echo",
        labelKey: "serial.echo.label",
        descriptionKey: "serial.echo.description",
        namespace: "moduleConfig",
      },
      {
        name: "rxd",
        labelKey: "serial.rxd.label",
        descriptionKey: "serial.rxd.description",
        namespace: "moduleConfig",
      },
      {
        name: "txd",
        labelKey: "serial.txd.label",
        descriptionKey: "serial.txd.description",
        namespace: "moduleConfig",
      },
      {
        name: "baud",
        labelKey: "serial.baud.label",
        descriptionKey: "serial.baud.description",
        namespace: "moduleConfig",
      },
      {
        name: "timeout",
        labelKey: "serial.timeout.label",
        descriptionKey: "serial.timeout.description",
        namespace: "moduleConfig",
      },
      {
        name: "mode",
        labelKey: "serial.mode.label",
        descriptionKey: "serial.mode.description",
        namespace: "moduleConfig",
      },
      {
        name: "overrideConsoleSerialPort",
        labelKey: "serial.overrideConsoleSerialPort.label",
        descriptionKey: "serial.overrideConsoleSerialPort.description",
        namespace: "moduleConfig",
      },
    ],
  },
  {
    section: "module",
    tab: "externalNotification",
    groupLabelKey: "externalNotification.title",
    groupNamespace: "moduleConfig",
    fields: [
      {
        name: "enabled",
        labelKey: "externalNotification.enabled.label",
        descriptionKey: "externalNotification.enabled.description",
        namespace: "moduleConfig",
      },
      {
        name: "outputMs",
        labelKey: "externalNotification.outputMs.label",
        descriptionKey: "externalNotification.outputMs.description",
        namespace: "moduleConfig",
      },
      {
        name: "output",
        labelKey: "externalNotification.output.label",
        descriptionKey: "externalNotification.output.description",
        namespace: "moduleConfig",
      },
      {
        name: "outputVibra",
        labelKey: "externalNotification.outputVibra.label",
        descriptionKey: "externalNotification.outputVibra.description",
        namespace: "moduleConfig",
      },
      {
        name: "outputBuzzer",
        labelKey: "externalNotification.outputBuzzer.label",
        descriptionKey: "externalNotification.outputBuzzer.description",
        namespace: "moduleConfig",
      },
      {
        name: "active",
        labelKey: "externalNotification.active.label",
        descriptionKey: "externalNotification.active.description",
        namespace: "moduleConfig",
      },
      {
        name: "alertMessage",
        labelKey: "externalNotification.alertMessage.label",
        descriptionKey: "externalNotification.alertMessage.description",
        namespace: "moduleConfig",
      },
      {
        name: "alertMessageVibra",
        labelKey: "externalNotification.alertMessageVibra.label",
        descriptionKey: "externalNotification.alertMessageVibra.description",
        namespace: "moduleConfig",
      },
      {
        name: "alertMessageBuzzer",
        labelKey: "externalNotification.alertMessageBuzzer.label",
        descriptionKey: "externalNotification.alertMessageBuzzer.description",
        namespace: "moduleConfig",
      },
      {
        name: "alertBell",
        labelKey: "externalNotification.alertBell.label",
        descriptionKey: "externalNotification.alertBell.description",
        namespace: "moduleConfig",
      },
      {
        name: "alertBellVibra",
        labelKey: "externalNotification.alertBellVibra.label",
        descriptionKey: "externalNotification.alertBellVibra.description",
        namespace: "moduleConfig",
      },
      {
        name: "alertBellBuzzer",
        labelKey: "externalNotification.alertBellBuzzer.label",
        descriptionKey: "externalNotification.alertBellBuzzer.description",
        namespace: "moduleConfig",
      },
      {
        name: "usePwm",
        labelKey: "externalNotification.usePwm.label",
        descriptionKey: "externalNotification.usePwm.description",
        namespace: "moduleConfig",
      },
      {
        name: "nagTimeout",
        labelKey: "externalNotification.nagTimeout.label",
        descriptionKey: "externalNotification.nagTimeout.description",
        namespace: "moduleConfig",
      },
      {
        name: "useI2sAsBuzzer",
        labelKey: "externalNotification.useI2sAsBuzzer.label",
        descriptionKey: "externalNotification.useI2sAsBuzzer.description",
        namespace: "moduleConfig",
      },
    ],
  },
  {
    section: "module",
    tab: "storeForward",
    groupLabelKey: "storeForward.title",
    groupNamespace: "moduleConfig",
    fields: [
      {
        name: "enabled",
        labelKey: "storeForward.enabled.label",
        descriptionKey: "storeForward.enabled.description",
        namespace: "moduleConfig",
      },
      {
        name: "heartbeat",
        labelKey: "storeForward.heartbeat.label",
        descriptionKey: "storeForward.heartbeat.description",
        namespace: "moduleConfig",
      },
      {
        name: "records",
        labelKey: "storeForward.records.label",
        descriptionKey: "storeForward.records.description",
        namespace: "moduleConfig",
      },
      {
        name: "historyReturnMax",
        labelKey: "storeForward.historyReturnMax.label",
        descriptionKey: "storeForward.historyReturnMax.description",
        namespace: "moduleConfig",
      },
      {
        name: "historyReturnWindow",
        labelKey: "storeForward.historyReturnWindow.label",
        descriptionKey: "storeForward.historyReturnWindow.description",
        namespace: "moduleConfig",
      },
    ],
  },
  {
    section: "module",
    tab: "rangeTest",
    groupLabelKey: "rangeTest.title",
    groupNamespace: "moduleConfig",
    fields: [
      {
        name: "enabled",
        labelKey: "rangeTest.enabled.label",
        descriptionKey: "rangeTest.enabled.description",
        namespace: "moduleConfig",
      },
      {
        name: "sender",
        labelKey: "rangeTest.sender.label",
        descriptionKey: "rangeTest.sender.description",
        namespace: "moduleConfig",
      },
      {
        name: "save",
        labelKey: "rangeTest.save.label",
        descriptionKey: "rangeTest.save.description",
        namespace: "moduleConfig",
      },
    ],
  },
  {
    section: "module",
    tab: "telemetry",
    groupLabelKey: "telemetry.title",
    groupNamespace: "moduleConfig",
    fields: [
      {
        name: "deviceUpdateInterval",
        labelKey: "telemetry.deviceUpdateInterval.label",
        descriptionKey: "telemetry.deviceUpdateInterval.description",
        namespace: "moduleConfig",
      },
      {
        name: "environmentUpdateInterval",
        labelKey: "telemetry.environmentUpdateInterval.label",
        descriptionKey: "telemetry.environmentUpdateInterval.description",
        namespace: "moduleConfig",
      },
      {
        name: "environmentMeasurementEnabled",
        labelKey: "telemetry.environmentMeasurementEnabled.label",
        descriptionKey: "telemetry.environmentMeasurementEnabled.description",
        namespace: "moduleConfig",
      },
      {
        name: "environmentScreenEnabled",
        labelKey: "telemetry.environmentScreenEnabled.label",
        descriptionKey: "telemetry.environmentScreenEnabled.description",
        namespace: "moduleConfig",
      },
      {
        name: "environmentDisplayFahrenheit",
        labelKey: "telemetry.environmentDisplayFahrenheit.label",
        descriptionKey: "telemetry.environmentDisplayFahrenheit.description",
        namespace: "moduleConfig",
      },
      {
        name: "airQualityEnabled",
        labelKey: "telemetry.airQualityEnabled.label",
        descriptionKey: "telemetry.airQualityEnabled.description",
        namespace: "moduleConfig",
      },
      {
        name: "airQualityInterval",
        labelKey: "telemetry.airQualityInterval.label",
        descriptionKey: "telemetry.airQualityInterval.description",
        namespace: "moduleConfig",
      },
      {
        name: "powerMeasurementEnabled",
        labelKey: "telemetry.powerMeasurementEnabled.label",
        descriptionKey: "telemetry.powerMeasurementEnabled.description",
        namespace: "moduleConfig",
      },
      {
        name: "powerUpdateInterval",
        labelKey: "telemetry.powerUpdateInterval.label",
        descriptionKey: "telemetry.powerUpdateInterval.description",
        namespace: "moduleConfig",
      },
      {
        name: "powerScreenEnabled",
        labelKey: "telemetry.powerScreenEnabled.label",
        descriptionKey: "telemetry.powerScreenEnabled.description",
        namespace: "moduleConfig",
      },
    ],
  },
  {
    section: "module",
    tab: "cannedMessage",
    groupLabelKey: "cannedMessage.title",
    groupNamespace: "moduleConfig",
    fields: [
      {
        name: "enabled",
        labelKey: "cannedMessage.moduleEnabled.label",
        descriptionKey: "cannedMessage.moduleEnabled.description",
        namespace: "moduleConfig",
      },
      {
        name: "rotary1Enabled",
        labelKey: "cannedMessage.rotary1Enabled.label",
        descriptionKey: "cannedMessage.rotary1Enabled.description",
        namespace: "moduleConfig",
      },
      {
        name: "inputbrokerPinA",
        labelKey: "cannedMessage.inputbrokerPinA.label",
        descriptionKey: "cannedMessage.inputbrokerPinA.description",
        namespace: "moduleConfig",
      },
      {
        name: "inputbrokerPinB",
        labelKey: "cannedMessage.inputbrokerPinB.label",
        descriptionKey: "cannedMessage.inputbrokerPinB.description",
        namespace: "moduleConfig",
      },
      {
        name: "inputbrokerPinPress",
        labelKey: "cannedMessage.inputbrokerPinPress.label",
        descriptionKey: "cannedMessage.inputbrokerPinPress.description",
        namespace: "moduleConfig",
      },
      {
        name: "inputbrokerEventCw",
        labelKey: "cannedMessage.inputbrokerEventCw.label",
        descriptionKey: "cannedMessage.inputbrokerEventCw.description",
        namespace: "moduleConfig",
      },
      {
        name: "inputbrokerEventCcw",
        labelKey: "cannedMessage.inputbrokerEventCcw.label",
        descriptionKey: "cannedMessage.inputbrokerEventCcw.description",
        namespace: "moduleConfig",
      },
      {
        name: "inputbrokerEventPress",
        labelKey: "cannedMessage.inputbrokerEventPress.label",
        descriptionKey: "cannedMessage.inputbrokerEventPress.description",
        namespace: "moduleConfig",
      },
      {
        name: "updown1Enabled",
        labelKey: "cannedMessage.updown1Enabled.label",
        descriptionKey: "cannedMessage.updown1Enabled.description",
        namespace: "moduleConfig",
      },
      {
        name: "allowInputSource",
        labelKey: "cannedMessage.allowInputSource.label",
        descriptionKey: "cannedMessage.allowInputSource.description",
        namespace: "moduleConfig",
      },
      {
        name: "sendBell",
        labelKey: "cannedMessage.sendBell.label",
        descriptionKey: "cannedMessage.sendBell.description",
        namespace: "moduleConfig",
      },
    ],
  },
  {
    section: "module",
    tab: "audio",
    groupLabelKey: "audio.title",
    groupNamespace: "moduleConfig",
    fields: [
      {
        name: "codec2Enabled",
        labelKey: "audio.codec2Enabled.label",
        descriptionKey: "audio.codec2Enabled.description",
        namespace: "moduleConfig",
      },
      {
        name: "pttPin",
        labelKey: "audio.pttPin.label",
        descriptionKey: "audio.pttPin.description",
        namespace: "moduleConfig",
      },
      {
        name: "bitrate",
        labelKey: "audio.bitrate.label",
        descriptionKey: "audio.bitrate.description",
        namespace: "moduleConfig",
      },
      {
        name: "i2sWs",
        labelKey: "audio.i2sWs.label",
        descriptionKey: "audio.i2sWs.description",
        namespace: "moduleConfig",
      },
      {
        name: "i2sSd",
        labelKey: "audio.i2sSd.label",
        descriptionKey: "audio.i2sSd.description",
        namespace: "moduleConfig",
      },
      {
        name: "i2sDin",
        labelKey: "audio.i2sDin.label",
        descriptionKey: "audio.i2sDin.description",
        namespace: "moduleConfig",
      },
      {
        name: "i2sSck",
        labelKey: "audio.i2sSck.label",
        descriptionKey: "audio.i2sSck.description",
        namespace: "moduleConfig",
      },
    ],
  },
  {
    section: "module",
    tab: "neighborInfo",
    groupLabelKey: "neighborInfo.title",
    groupNamespace: "moduleConfig",
    fields: [
      {
        name: "enabled",
        labelKey: "neighborInfo.enabled.label",
        descriptionKey: "neighborInfo.enabled.description",
        namespace: "moduleConfig",
      },
      {
        name: "updateInterval",
        labelKey: "neighborInfo.updateInterval.label",
        descriptionKey: "neighborInfo.updateInterval.description",
        namespace: "moduleConfig",
      },
    ],
  },
  {
    section: "module",
    tab: "ambientLighting",
    groupLabelKey: "ambientLighting.title",
    groupNamespace: "moduleConfig",
    fields: [
      {
        name: "ledState",
        labelKey: "ambientLighting.ledState.label",
        descriptionKey: "ambientLighting.ledState.description",
        namespace: "moduleConfig",
      },
      {
        name: "current",
        labelKey: "ambientLighting.current.label",
        descriptionKey: "ambientLighting.current.description",
        namespace: "moduleConfig",
      },
      {
        name: "red",
        labelKey: "ambientLighting.red.label",
        descriptionKey: "ambientLighting.red.description",
        namespace: "moduleConfig",
      },
      {
        name: "green",
        labelKey: "ambientLighting.green.label",
        descriptionKey: "ambientLighting.green.description",
        namespace: "moduleConfig",
      },
      {
        name: "blue",
        labelKey: "ambientLighting.blue.label",
        descriptionKey: "ambientLighting.blue.description",
        namespace: "moduleConfig",
      },
    ],
  },
  {
    section: "module",
    tab: "detectionSensor",
    groupLabelKey: "detectionSensor.title",
    groupNamespace: "moduleConfig",
    fields: [
      {
        name: "enabled",
        labelKey: "detectionSensor.enabled.label",
        descriptionKey: "detectionSensor.enabled.description",
        namespace: "moduleConfig",
      },
      {
        name: "minimumBroadcastSecs",
        labelKey: "detectionSensor.minimumBroadcastSecs.label",
        descriptionKey: "detectionSensor.minimumBroadcastSecs.description",
        namespace: "moduleConfig",
      },
      {
        name: "stateBroadcastSecs",
        labelKey: "detectionSensor.stateBroadcastSecs.label",
        descriptionKey: "detectionSensor.stateBroadcastSecs.description",
        namespace: "moduleConfig",
      },
      {
        name: "sendBell",
        labelKey: "detectionSensor.sendBell.label",
        descriptionKey: "detectionSensor.sendBell.description",
        namespace: "moduleConfig",
      },
      {
        name: "name",
        labelKey: "detectionSensor.name.label",
        descriptionKey: "detectionSensor.name.description",
        namespace: "moduleConfig",
      },
      {
        name: "monitorPin",
        labelKey: "detectionSensor.monitorPin.label",
        descriptionKey: "detectionSensor.monitorPin.description",
        namespace: "moduleConfig",
      },
      {
        name: "detectionTriggerType",
        labelKey: "detectionSensor.detectionTriggerType.label",
        descriptionKey: "detectionSensor.detectionTriggerType.description",
        namespace: "moduleConfig",
      },
      {
        name: "usePullup",
        labelKey: "detectionSensor.usePullup.label",
        descriptionKey: "detectionSensor.usePullup.description",
        namespace: "moduleConfig",
      },
    ],
  },
  {
    section: "module",
    tab: "paxcounter",
    groupLabelKey: "paxcounter.title",
    groupNamespace: "moduleConfig",
    fields: [
      {
        name: "enabled",
        labelKey: "paxcounter.enabled.label",
        descriptionKey: "paxcounter.enabled.description",
        namespace: "moduleConfig",
      },
      {
        name: "paxcounterUpdateInterval",
        labelKey: "paxcounter.paxcounterUpdateInterval.label",
        descriptionKey: "paxcounter.paxcounterUpdateInterval.description",
        namespace: "moduleConfig",
      },
      {
        name: "wifiThreshold",
        labelKey: "paxcounter.wifiThreshold.label",
        descriptionKey: "paxcounter.wifiThreshold.description",
        namespace: "moduleConfig",
      },
      {
        name: "bleThreshold",
        labelKey: "paxcounter.bleThreshold.label",
        descriptionKey: "paxcounter.bleThreshold.description",
        namespace: "moduleConfig",
      },
    ],
  },
];
