name: Push commit to schema registry

permissions:
  contents: read

on:
  push:
    branches:
      - master

jobs:
  push_to_registry:
    name: Push to schema registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Push to schema registry
        uses: bufbuild/buf-action@v1.2.0
        with:
          github_token: ${{ github.token }}
          token: ${{ secrets.BUF_TOKEN }}
          push: true
