name: Push new version to schema registry

permissions:
  contents: read

on:
  push:
    tags:
      - "**"

jobs:
  push_to_registry:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Buf
        uses: bufbuild/buf-action@v1.2.0
        with:
          github_token: ${{ github.token }}
          token: ${{ secrets.BUF_TOKEN }}
          setup_only: true

      - name: Push to schema registry
        env:
          BUF_TOKEN: ${{ secrets.BUF_TOKEN }}
        run: |
          buf push --tag ${{ github.ref_name }}
