name: Pull Request

on:
  push:
    paths:
      - "packages/core"
      - "packages/transport-deno"
      - "packages/transport-http"
      - "packages/transport-web-bluetooth"
      - "packages/transport-web-serial"
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Check formatting
        run: deno fmt --check

      - name: Check types
        run: deno lint

      - name: Publish to JSR
        run: npx jsr publish
